server:
  port: 6844

spring.redis:
    database: 0
    host: localhost
    port: 6379

spring.session:
    store-type: redis
    timeout: 3000
    redis:
        cleanup-cron: 0 * * * * *
        flush-mode: on-save
        namespace: uiapp:session

zuul:
  routes:
    client-app:
      path: /app/**
      sensitiveHeaders:
      url: http://localhost:8082
    auth:
      path: /auth/**
      sensitiveHeaders:
      url: http://localhost:8080

security:
  oauth2:
    client:
      client-id: devapp
      client-secret: password
      access-token-uri: http://localhost:8080/oauth/token
      userAuthorizationUri: http://localhost:8080/oauth/authorize
    resource:
      user-info-uri: http://localhost:8080/user

spring.main.allow-bean-definition-overriding: true
